"""Create alternative group assignments for the Week 3 predictor dataset.

The point of this script is split robustness: keep the features, labels and
group structure fixed, and only redraw which groups land in train/validation/
test.  A group (one task's original/better/worse records) always moves as a
unit, so the resulting file is a drop-in replacement for ``splits.json``.

The split logic is delegated to ``probe.data.build_week3_dataset.make_splits``
so an alternative split is generated by exactly the same code path as the
original one -- only the seed differs.  That keeps the comparison honest: any
change in the results comes from the group assignment, not from a subtly
different splitting rule.

Usage
-----
Write two alternative splits beside a dataset:

    python -m probe.data.resplit_week3 \\
        --dataset-dir data/week3_12retry_7suite_boundary_only/dataset \\
        --output-dir data/week3_12retry_7suite_boundary_only/splits \\
        --seed 20260917 --name resplit_a \\
        --seed 20260918 --name resplit_b

Then train against one of them:

    python -m probe.data.train_week3_predictors \\
        --dataset-dir <dataset> \\
        --splits-path <dataset>/../splits/resplit_a.json \\
        --output-dir <out> ...

Each output file records the seed that produced it, and every run is checked
against the invariants the training code relies on (one group per split, all
three conditions present).
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from probe.data.build_week3_dataset import make_splits
from probe.data.train_week3_predictors import (
    CONDITION_ORDER,
    infer_records_per_group,
    read_jsonl,
)

LOGGER = logging.getLogger(__name__)
DEFAULT_FRACTIONS = (0.7, 0.15)


def summarize_split(
    split_payload: dict[str, Any],
    records: list[dict[str, Any]],
) -> dict[str, Any]:
    """Describe a split and assert the invariants training depends on."""

    group_to_split: dict[str, str] = {}
    for split in ("train", "validation", "test"):
        for group_id in split_payload["groups"][split]:
            group_id = str(group_id)
            if group_id in group_to_split:
                raise ValueError(f"group {group_id} appears in two splits")
            group_to_split[group_id] = split

    record_to_split: dict[str, str] = {}
    for split in ("train", "validation", "test"):
        for record_id in split_payload["record_ids"][split]:
            record_id = str(record_id)
            if record_id in record_to_split:
                raise ValueError(f"record {record_id} appears in two splits")
            record_to_split[record_id] = split

    by_group: dict[str, list[dict[str, Any]]] = {}
    for record in records:
        by_group.setdefault(str(record["group_id"]), []).append(record)

    for group_id, members in by_group.items():
        if group_id not in group_to_split:
            raise ValueError(f"group {group_id} is missing from the split")
        conditions = {str(member["condition_id"]) for member in members}
        if conditions != set(CONDITION_ORDER):
            raise ValueError(
                f"group {group_id}: conditions {sorted(conditions)} != "
                f"{sorted(CONDITION_ORDER)}"
            )
        splits_seen = {record_to_split.get(str(m["record_id"])) for m in members}
        if len(splits_seen) != 1:
            raise ValueError(
                f"group {group_id} straddles splits: {sorted(splits_seen)}"
            )

    suite_of = {
        str(record["group_id"]): str(record.get("suite"))
        for record in records
    }
    suite_counts: dict[str, Counter] = {}
    for group_id, split in group_to_split.items():
        suite_counts.setdefault(suite_of.get(group_id, "?"), Counter())[split] += 1

    return {
        "split_seed": split_payload["split_seed"],
        "fractions": split_payload["fractions"],
        "group_counts": {
            split: len(split_payload["groups"][split])
            for split in ("train", "validation", "test")
        },
        "record_counts": {
            split: len(split_payload["record_ids"][split])
            for split in ("train", "validation", "test")
        },
        "suite_group_counts": {
            suite: dict(sorted(counts.items()))
            for suite, counts in sorted(suite_counts.items())
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--seed",
        type=int,
        action="append",
        required=True,
        help="repeat once per alternative split; order pairs with --name",
    )
    parser.add_argument(
        "--name",
        action="append",
        required=True,
        help="output stem per split, e.g. resplit_a; order pairs with --seed",
    )
    parser.add_argument("--train-fraction", type=float, default=DEFAULT_FRACTIONS[0])
    parser.add_argument(
        "--validation-fraction", type=float, default=DEFAULT_FRACTIONS[1]
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(name)s:%(message)s")

    if len(args.seed) != len(args.name):
        raise SystemExit("--seed and --name must be given the same number of times")
    if len(set(args.name)) != len(args.name):
        raise SystemExit("--name values must be unique")

    dataset_dir = args.dataset_dir.expanduser().resolve()
    manifest_path = dataset_dir / "manifest.jsonl"
    if not manifest_path.exists():
        raise SystemExit(f"manifest not found: {manifest_path}")
    records = read_jsonl(manifest_path)
    if not records:
        raise SystemExit(f"{manifest_path}: no records")

    # The manifest is reused unchanged; only the group assignment is redrawn.
    records_per_group = infer_records_per_group(records)

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    for name, seed in zip(args.name, args.seed):
        payload = make_splits(
            records,
            seed=seed,
            train_fraction=args.train_fraction,
            validation_fraction=args.validation_fraction,
        )
        summary = summarize_split(payload, records)
        payload["generated_by"] = "probe.data.resplit_week3"
        payload["dataset_dir"] = str(dataset_dir)
        payload["records_per_group"] = records_per_group
        payload["resplit_summary"] = summary

        path = output_dir / f"{name}.json"
        path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        counts = summary["group_counts"]
        LOGGER.info(
            "wrote %s (seed=%s): train=%d validation=%d test=%d groups",
            path,
            seed,
            counts["train"],
            counts["validation"],
            counts["test"],
        )


if __name__ == "__main__":
    sys.exit(main())
